### ISSUE TITLE
Update to list Gatsby v3 as a peer dependency

### ISSUE THREAD

**Issue by rogervera** [Js-Brecht/gatsby-plugin-tsconfig-paths#2]
Haven't looked into any breaking changes that could occur yet, but Gatsby v3 just released.

See: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers

https://github.com/Js-Brecht/gatsby-plugin-tsconfig-paths/blob/f2fbf252085414aaff8258fea5995179b662bdfd/package.json#L40

**Comment by Js-Brecht** [comment]
Published in release v1.0.3
