### ISSUE TITLE
Doesn't work with Gatsby 5

### ISSUE THREAD

**Issue by 340rahul** [Js-Brecht/gatsby-plugin-tsconfig-paths#8]
Unable to install for Gatsby 5. I guess the gatsby dependency needs to be updated.

[package.json](https://github.com/Js-Brecht/gatsby-plugin-tsconfig-paths/blob/master/package.json#L42)

**Comment by artola** [comment]
@Js-Brecht Could you please release a version with support for v5 ?  (it is already in master since [commit](https://github.com/Js-Brecht/gatsby-plugin-tsconfig-paths/commit/74d2702fdedb4206926bb4b1ecb397ff7865a9bf))

**Comment by xtellurian** [comment]
Bump. Please release the version.

**Comment by Js-Brecht** [comment]
Better yet: somebody could write a PR that incorporates automatic publishing on pushes to the `production` branch

**Comment by Js-Brecht** [comment]
Shipped in [v1.0.6](https://github.com/Js-Brecht/gatsby-plugin-tsconfig-paths/releases/tag/v1.0.6)
